version: '3.8'

services:
  eli5bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/last_seen_id.txt') or not os.path.exists('/app/data') else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: ["python", "src/main.py"]

  eli5api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]
